version: '3.9'

services:
  api:
    image: tyskerdocker/javalin-auth-api:latest
    container_name: api
    restart: unless-stopped
    networks:
      - frontend
      - backend
    environment:
      CONNECTION_STR: jdbc:postgresql://db:5432/
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DEPLOYED: TRUE
      SECRET_KEY: 841D8A6C80CBA4FCAD32D5367C18C53B
      TOKEN_EXPIRE_TIME: 1800000
      ISSUER: cphbusiness.dk
    ports:
      - "7070:7070"

  web:
    image: tyskerdocker/frontendsecure:latest
    container_name: web
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - frontend

  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

networks:
  frontend:
    name: frontend
    driver: bridge
  backend:
    name: backend
    driver: bridge
